

export type PermissionType =
  | "dashboard_view"
  | "dashboard_llm_view"
  | "dashboard_user_view"
  | "configs_view"
  | "configs_role_params_view"
  | "configs_role_params_edit"
  | "configs_image_params_view"
  | "configs_image_params_edit"
  | "configs_i18n_view"
  | "configs_i18n_edit"
  | "configs_token_consume_view"
  | "configs_token_consume_edit"
  | "configs_membership_view"
  | "configs_membership_edit"
  | "configs_coins_view"
  | "configs_coins_edit"
  | "configs_gifts_view"
  | "configs_gifts_create"
  | "configs_gifts_edit"
  | "configs_gifts_delete"
  | "configs_daily_tasks_view"
  | "configs_daily_tasks_edit"
  | "configs_legal_view"
  | "configs_legal_edit"
  | "roles_view"
  | "roles_create"
  | "roles_edit"
  | "roles_delete"
  | "roles_review"
  | "permission_view"
  | "permission_roles_view"
  | "permission_roles_create"
  | "permission_roles_edit"
  | "permission_roles_delete"
  | "permission_users_view"
  //管理员权限
  | "permission_users_create"
  | "permission_users_edit"
  | "permission_users_delete";
