words:
  - cdkey
  - errows
  - errowsctl
  - futa
  - ILIKE
  - ORDINALITY
  - TSTZRANGE
  - vitest
ignoreWords:
  - uids
  - btree_gist
  - citext
  - pgcrypto
  - charactergender
ignorePaths:
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/.git/**"
  - "**/.venv/**"
