location /api/ {
  access_log /var/log/nginx/errows/api.access.log;
  error_log  /var/log/nginx/errows/api.error.log warn;

  proxy_set_header X-Real-IP       $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

	rewrite ^ $request_uri;
	rewrite ^/api/(.*) $1 break;
	return 400;

  proxy_pass                       http://errows_api/$uri;
}