include /srv/etc/nginx/snippets/api.conf;
include /srv/etc/nginx/snippets/assets.conf;
include /srv/etc/nginx/snippets/grafana.conf;

access_log /var/log/nginx/errows/console.access.log;
error_log  /var/log/nginx/errows/console.error.log warn;

client_max_body_size 1000M;
send_timeout 20m;
proxy_read_timeout 20m;

root /srv/services/$instance/errows-console/;
location / {
  try_files $uri $uri/ /index.html;
}