{
 "title": "ai 接口统计",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "query": {
     "query": "label_values(ai_request_count,endpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "请求总数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(endpoint) (ai_request_count{endpoint=\"$endpoint\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "失败数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(endpoint) (ai_request_count{status=\"failed\", endpoint=\"$endpoint\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "请求失败率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ai_request_count{endpoint=\"$endpoint\", status=\"failed\"}) / sum(ai_request_count{endpoint=\"$endpoint\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "平均响应时间",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ai_request_time{endpoint=\"$endpoint\"})",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "AI 接口请求",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "ai_request_count{endpoint=\"$endpoint\"}",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}