const FIXED_TAGS_ORDER = [
  "Realistic",
  "Anime",
  "Female",
  "Male",
  "African",
  "Angel",
  "Anime World",
  "Armor",
  "Asian",
  "Beast ears",
  "Beastkin",
  "Black-haired",
  "Blonde",
  "Blue-haired",
  "Braided",
  "Brunette",
  "Casual Wear",
  "Caucasian",
  "Centaur",
  "Cheerful",
  "Cold",
  "Curly hair",
  "Curvy",
  "Dark-skinned",
  "Demon",
  "Deredere",
  "Dragon",
  "Elf",
  "Energetic",
  "Errows World",
  "Fair-skinned",
  "Fairy",
  "Formal Wear",
  "Futa",
  "Gentle",
  "Glasses",
  "Gloves",
  "Gothic Outfit",
  "Green-haired",
  "Harpy",
  "Hats",
  "Horns",
  "Human",
  "Innocent",
  "Intelligent",
  "Introverted",
  "Lamia",
  "Large-breasted",
  "Latina",
  "Lazy",
  "Long-haired",
  "Mage Outfit",
  "Maid Outfit",
  "Mature",
  "Orange-haired",
  "Pink-haired",
  "Ponytail",
  "Purple-haired",
  "Red-haired",
  "School Uniform",
  "Seductive Wear",
  "Short-haired",
  "Silver-haired",
  "Slim",
  "Slime",
  "Stockings",
  "Straight hair",
  "Tail",
  "Tall",
  "Tanned",
  "Twin-tails",
  "Uniform",
  "Vampire",
  "White-haired",
  "Wings",
] as const;

export const CHARACTER_SEARCH_TAG_OPTIONS: { value: string; label: string }[] =
  FIXED_TAGS_ORDER.map((tag) => ({ value: tag, label: tag }));
