export const CREATE_ROLE_DICT = {
    "titles": {
        "gender": "选择性别",
        "type": "选择风格",
        "assortment": "选择种类",
        "race": "毛茸茸种族",
        "age": "选择年龄",
        "eye_color": "选择眼睛颜色*",
        "hair_style": "选择发型*",
        "hair_color": "选择发色",
        "hair_length": "选择头发长度",
        "hair_bangs": "选择刘海",
        "body_type": "选择体型",
        "penis_size": "选择阴茎尺寸",
        "breast_size": "选择胸部尺寸",
        "butt_size": "选择臀部尺寸",
        "introduction": "介绍",
        "tags": "标签",
        "voice": "选择声音",
        "nickname": "名字",
        "name": "名字",
        "settings": "角色设定",
        "greeting": "问候",
        "personality": "性格",
        "scenario": "场景",
        "conversation": "示例对话"
    },
    "labels": {
        "Male": "男性",
        "Female": "女性",
        "Realistic": "写实",
        "Anime": "动漫",
        "Human": "人类",
        "Dragon": "龙",
        "Furry": "兽人",
        "Elf": "精灵",
        "Beastkin": "兽族",
        "Demonkin": "魔族",
        "Fairy": "仙灵",
        "Angelkin": "天使族",
        "Angel": "天使",
        "Dog Man": "狗人",
        "Cat Man": "猫人",
        "Werewolf": "狼人",
        "Rabbit man": "兔人",
        "High Elf": "高等精灵",
        "Dark Elf": "暗黑精灵",
        "Red Dragon": "红龙",
        "Blue Dragon": "蓝龙",
        "Black Dragon": "黑龙",
        "White Dragon": "白龙",
        "Gold Dragon": "金龙",
        "Asain": "亚洲人",
        "Caucasian": "高加索人",
        "African": "非洲人",
        "Latina": "拉丁裔",
        "Fallen Angel": "堕落天使",
        "Wolf man": "狼人",
        "Centaur": "半人马",
        "Dog man": "狗人",
        "Fiary king": "仙灵王",
        "Succubus": "魅魔",
        "Demon": "恶魔",
        "Oni": "鬼",
        "Vampire": "吸血鬼",
        "Cat girl": "猫娘",
        "Dog girl": "狗娘",
        "Harpy": "鹰身女妖",
        "Lamia": "蛇女",
        "Cow Girl": "牛娘",
        "Rabbit Girl": "兔娘",
        "Wolf girl": "狼娘",
        "Cat": "猫",
        "Tiger": "老虎",
        "Horse": "马",
        "Leopard": "豹",
        "Rabbit": "兔子",
        "Asian": "亚洲人",
        "Teen(18+)": "青少年(18+)",
        "20s": "20多岁",
        "30s": "30多岁",
        "40-55": "40-55岁",
        "18+": "18+",
        "Green": "绿色",
        "Black eye": "黑色眼睛",
        "Blue eye": "蓝色眼睛",
        "Brown eye": "棕色眼睛",
        "Red  eye": "红色眼睛",
        "Black": "黑色",
        "Blue": "蓝色",
        "Red": "红色",
        "Yellow": "黄色",
        "White": "白色",
        "Brown": "棕色",
        "Pink": "粉色",
        "Purple": "紫色",
        "Gray": "灰色",
        "Short Hair": "短发",
        "Long Hair": "长发",
        "Messy hair": "凌乱发型",
        "Pony Tail": "马尾",
        "Bob Cut": "波波头",
        "Dreadlocks": "脏辫",
        "Punk Hair": "朋克发型",
        "Medium ponytail": "中马尾",
        "Side ponytail": "侧马尾",
        "Lolita Curls": "洛丽塔卷发",
        "Twin Braids": "双麻花辫",
        "Mohawk": "莫霍克发型",
        "Punk hair": "朋克发型",
        "Half-up Hair": "半扎发",
        "Half-up Bun": "半丸子头",
        "Curly Hair": "卷发",
        "Double bun hair": "双丸子头",
        "Straight": "直发",
        "Low ponytail": "低马尾",
        "Twintail": "双马尾",
        "Bun hair": "丸子头",
        "High ponytail": "高马尾",
        "Wavy Hair": "波浪发",
        "Round Bob": "圆波波头",
        "Blunt Cut": "齐刘海",
        "Braid": "辫子",
        "Blonde": "金发",
        "Brunette": "棕发",
        "Short hair": "短发",
        "Medium Hair": "中等长度头发",
        "long hair": "长发",
        "Extra Long Hair": "超长发",
        "Middle-part Forehair": "中分刘海",
        "Choppy bangs": "碎刘海",
        "Side Bangs": "侧刘海",
        "Open Forehead": "露额头",
        "Blunt Bangs": "齐刘海",
        "Asymmetrical Bangs": "不对称刘海",
        "Petite": "娇小",
        "Slim": "苗条",
        "Athletic": "健美",
        "Voluptuous": "丰满",
        "Curvy": "曲线美",
        "Muscular": "肌肉发达",
        "Chubby": "微胖",
        "Small Penis": "小阴茎",
        "Midium Penis": "中等阴茎",
        "Big penis": "大阴茎",
        "Flat": "平坦",
        "Small": "小",
        "Medium": "中等",
        "Large": "大",
        "Giant": "巨大",
        "Example 1": "示例 1",
        "Example 2": "示例 2",
        "Example 3": "示例 3",
        "Example 4": "示例 4",
        "Example 5": "示例 5",
        "Errows World": "Errows 世界",
        "Anime World": "动漫世界",
        "Futa": "扶她",
        "Fantasy Creatures": "幻想生物",
        "undead": "不死族",
        "Finfolk": "鱼人",
        "Android": "机器人",
        "Spirit": "灵体",
        "Dwarf": "矮人",
        "vampire": "吸血鬼",
        "Slime": "史莱姆",
        "Twist braid": "扭辫",
        "Hair bun": "发髻",
        "Braided": "编发",
        "Straight hair": "直发",
        "Curly hair": "卷发",
        "Ponytail": "马尾",
        "Twin-tails": "双马尾",
        "Long-haired": "长发",
        "Short-haired": "短发",
        "Orange-haired": "橙发",
        "Purple-haired": "紫发",
        "Green-haired": "绿发",
        "Red-haired": "红发",
        "White-haired": "白发",
        "Silver-haired": "银发",
        "Pink-haired": "粉发",
        "Blue-haired": "蓝发",
        "Black-haired": "黑发",
        "Tall": "高个子",
        "Horns": "犄角",
        "Wings": "翅膀",
        "Tail": "尾巴",
        "Beast ears": "兽耳",
        "Large-breasted": "大胸",
        "Medium-breasted": "中等胸部",
        "Small-breasted": "小胸",
        "Flat-breasted": "平胸",
        "Dark-skinned": "深色皮肤",
        "Tanned": "晒黑皮肤",
        "Fair-skinned": "白皙皮肤",
        "Stockings": "长筒袜",
        "Gloves": "手套",
        "Hats": "帽子",
        "Glasses": "眼镜",
        "Seductive Wear": "诱惑装",
        "Gothic Outfit": "哥特装",
        "Formal Wear": "正装",
        "Armor": "盔甲",
        "Maid Outfit": "女仆装",
        "School Uniform": "校服",
        "Mage Outfit": "法师袍",
        "Casual Wear": "休闲装",
        "Uniform": "制服",
        "Lazy": "懒散",
        "Gentle": "温柔",
        "Mature": "成熟",
        "Deredere": "温柔系",
        "Intelligent": "聪明",
        "Innocent": "天真",
        "Energetic": "活力",
        "Cold": "冷酷",
        "Introverted": "内向",
        "Cheerful": "开朗",
        "Voice 1": "声音 1",
        "Voice 2": "声音 2",
        "Voice 3": "声音 3",
        "Voice 4": "声音 4",
        "Voice 5": "声音 5",
        "Voice 6": "声音 6",
        "Voice 7": "声音 7",
        "Voice 8": "声音 8",
        "hairColor": "发色"
    },
    "inputExample": {
        "Example 1": "characterExamples.example1.zh",
        "Example 2": "characterExamples.example2.zh",
        "Example 3": "characterExamples.example3.zh",
        "Example 4": "characterExamples.example4.zh",
        "Example 5": "characterExamples.example5.zh"
    }
}