#!/usr/bin/env node

import yargs from 'yargs';
import path, { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { hideBin } from 'yargs/helpers';
import commands from './cmds.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));

yargs(hideBin(process.argv))
.options({
  'd': {
    alias: 'dir',
    demandOption: false,
    default: path.join(__dirname, '..', 'config'),
    type: 'string',
    describe: '配置文件目录'
  },
  'c': {
    alias: 'conf',
    demandOption: false,
    default: 'development',
    type: 'string',
    describe: '配置类型',
    choices: ['development', 'production']
  },
  v: {
    alias: 'verbose',
    type: 'boolean',
    default: false,
    describe: '启用详细日志'
  }
})
.command(commands)
.demandCommand()
.usage('$0 <command> [options]')
.help(true)
.wrap(72)
.showHelpOnFail(true)
.strict()
.parse();
